//! Persistence layer – SQLite via `rusqlite` (bundled build).
//!
//! The public API is intentionally synchronous and designed to be driven
//! from a dedicated background thread, keeping the GUI responsive.
//!
//! ## Schema
//!
//! ```text
//! system_logs        – one row per monitoring cycle (CPU/memory/network totals)
//! process_snapshots  – top processes per cycle (FK → system_logs)
//! risk_alerts        – persisted alerts generated by the risk engine
//! ```

use anyhow::{Context, Result};
use rusqlite::{params, Connection};

use crate::models::{RiskAlert, SystemSnapshot};

// ─── Schema DDL ──────────────────────────────────────────────────────────────

const SCHEMA_SQL: &str = "
PRAGMA journal_mode = WAL;
PRAGMA synchronous  = NORMAL;

CREATE TABLE IF NOT EXISTS system_logs (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp       TEXT    NOT NULL,
    cpu_usage       REAL    NOT NULL,
    memory_used_kb  INTEGER NOT NULL,
    memory_total_kb INTEGER NOT NULL,
    swap_used_kb    INTEGER NOT NULL,
    swap_total_kb   INTEGER NOT NULL,
    net_rx_bytes    INTEGER NOT NULL,
    net_tx_bytes    INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS process_snapshots (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    log_id      INTEGER NOT NULL REFERENCES system_logs(id) ON DELETE CASCADE,
    pid         INTEGER NOT NULL,
    name        TEXT    NOT NULL,
    cpu_usage   REAL    NOT NULL,
    memory_kb   INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS risk_alerts (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp    TEXT    NOT NULL,
    risk_level   TEXT    NOT NULL,
    category     TEXT    NOT NULL,
    description  TEXT    NOT NULL,
    process_pid  INTEGER,
    process_name TEXT,
    acknowledged INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_system_logs_ts    ON system_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_risk_alerts_ts    ON risk_alerts(timestamp);
CREATE INDEX IF NOT EXISTS idx_risk_alerts_level ON risk_alerts(risk_level);
";

// ─── Database Handle ─────────────────────────────────────────────────────────

pub struct Database {
    conn: Connection,
}

impl Database {
    /// Open (or create) the SQLite database at `path` and apply the schema.
    pub fn open(path: &str) -> Result<Self> {
        let conn =
            Connection::open(path).with_context(|| format!("Cannot open database at '{path}'"))?;

        conn.execute_batch(SCHEMA_SQL)
            .context("Failed to apply database schema")?;

        log::info!("Database opened at '{path}'");
        Ok(Self { conn })
    }

    // ── Insert a full system snapshot ────────────────────────────────────────

    /// Persist a `SystemSnapshot`. Inserts a row into `system_logs` and up to
    /// `top_n` processes (sorted by CPU) into `process_snapshots`.
    pub fn insert_snapshot(&self, snapshot: &SystemSnapshot, top_n: usize) -> Result<i64> {
        let ts = snapshot.timestamp.to_rfc3339();

        // Aggregate network totals across all interfaces.
        let net_rx: u64 = snapshot.network.iter().map(|n| n.bytes_received).sum();
        let net_tx: u64 = snapshot.network.iter().map(|n| n.bytes_transmitted).sum();

        self.conn
            .execute(
                "INSERT INTO system_logs
                 (timestamp, cpu_usage, memory_used_kb, memory_total_kb,
                  swap_used_kb, swap_total_kb, net_rx_bytes, net_tx_bytes)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
                params![
                    ts,
                    snapshot.cpu.global_usage_percent as f64,
                    snapshot.memory.used_bytes / 1024,
                    snapshot.memory.total_bytes / 1024,
                    snapshot.memory.swap_used_bytes / 1024,
                    snapshot.memory.swap_total_bytes / 1024,
                    net_rx as i64,
                    net_tx as i64,
                ],
            )
            .context("insert_snapshot: system_logs INSERT failed")?;

        let log_id = self.conn.last_insert_rowid();

        // Top N processes sorted by CPU.
        let mut processes = snapshot.processes.clone();
        processes.sort_by(|a, b| {
            b.cpu_usage_percent
                .partial_cmp(&a.cpu_usage_percent)
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        for proc in processes.iter().take(top_n) {
            self.conn
                .execute(
                    "INSERT INTO process_snapshots (log_id, pid, name, cpu_usage, memory_kb)
                 VALUES (?1, ?2, ?3, ?4, ?5)",
                    params![
                        log_id,
                        proc.pid as i64,
                        &proc.name,
                        proc.cpu_usage_percent as f64,
                        proc.memory_bytes as i64 / 1024,
                    ],
                )
                .context("insert_snapshot: process_snapshots INSERT failed")?;
        }

        log::debug!(
            "Snapshot logged (log_id={log_id}, processes={})",
            processes.len().min(top_n)
        );
        Ok(log_id)
    }

    // ── Insert a risk alert ──────────────────────────────────────────────────

    /// Persist a `RiskAlert` to the database.
    pub fn insert_alert(&self, alert: &RiskAlert) -> Result<i64> {
        self.conn.execute(
            "INSERT INTO risk_alerts
                 (timestamp, risk_level, category, description, process_pid, process_name, acknowledged)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
            params![
                alert.timestamp.to_rfc3339(),
                serde_json::to_string(&alert.risk_level)?,
                serde_json::to_string(&alert.category)?,
                &alert.description,
                alert.process_pid.map(|p| p as i64),
                alert.process_name.as_deref(),
                0_i32,
            ],
        )
        .context("insert_alert: risk_alerts INSERT failed")?;

        let id = self.conn.last_insert_rowid();
        log::debug!("Alert persisted (db_id={id}, level={:?})", alert.risk_level);
        Ok(id)
    }

    // ── Acknowledge an alert ─────────────────────────────────────────────────

    #[allow(dead_code)]
    pub fn acknowledge_alert(&self, db_id: i64) -> Result<()> {
        self.conn
            .execute(
                "UPDATE risk_alerts SET acknowledged = 1 WHERE id = ?1",
                params![db_id],
            )
            .context("acknowledge_alert failed")?;
        Ok(())
    }

    // ── Query helpers ────────────────────────────────────────────────────────

    /// Returns the total number of snapshots stored.
    pub fn snapshot_count(&self) -> Result<i64> {
        let count: i64 = self
            .conn
            .query_row("SELECT COUNT(*) FROM system_logs", [], |r| r.get(0))
            .context("snapshot_count query failed")?;
        Ok(count)
    }

    /// Returns the total number of alerts stored.
    #[allow(dead_code)]
    pub fn alert_count(&self) -> Result<i64> {
        let count: i64 = self
            .conn
            .query_row("SELECT COUNT(*) FROM risk_alerts", [], |r| r.get(0))
            .context("alert_count query failed")?;
        Ok(count)
    }

    /// Returns the last N system log rows as raw tuples for quick reporting.
    #[allow(dead_code)]
    pub fn recent_logs(&self, n: usize) -> Result<Vec<(String, f64, i64, i64)>> {
        let mut stmt = self.conn.prepare(
            "SELECT timestamp, cpu_usage, memory_used_kb, memory_total_kb
             FROM system_logs
             ORDER BY id DESC
             LIMIT ?1",
        )?;
        let rows = stmt
            .query_map(params![n as i64], |r| {
                Ok((r.get::<_, String>(0)?, r.get(1)?, r.get(2)?, r.get(3)?))
            })?
            .collect::<rusqlite::Result<Vec<_>>>()
            .context("recent_logs query failed")?;
        Ok(rows)
    }

    /// Prune old system_logs rows, keeping only the most recent `keep` rows.
    pub fn prune_old_logs(&self, keep: usize) -> Result<usize> {
        let deleted = self
            .conn
            .execute(
                "DELETE FROM system_logs
             WHERE id NOT IN (
                 SELECT id FROM system_logs ORDER BY id DESC LIMIT ?1
             )",
                params![keep as i64],
            )
            .context("prune_old_logs failed")?;
        if deleted > 0 {
            log::info!("Pruned {deleted} old log entries from database");
        }
        Ok(deleted)
    }
}
